#!/bin/sh

read -r tty < /sys/class/tty/tty0/active
vt=vt$(echo "$tty" | sed -e 's/tty//g')
user=$(who | grep "$tty" | cut -d' ' -f1)
xorg=$(pgrep -a -U "$user" -t "$tty" Xorg | grep "$vt")

[ -z "$xorg" ] && exit

DISPLAY=$(echo "$xorg" | grep -o ':[0-9]')
export DISPLAY

pa=$(pgrep -U "$user" pulseaudio)
env=$(tr '\0' '\n' < "/proc/$pa/environ")

PULSE_RUNTIME_PATH=$(echo "$env" | grep '^PULSE_RUNTIME_PATH=' | cut -d= -f2)
if [ -n "$PULSE_RUNTIME_PATH" ]; then
	export PULSE_RUNTIME_PATH
else
	XDG_RUNTIME_DIR=$(echo "$env" | grep '^XDG_RUNTIME_DIR=' | cut -d= -f2)
	[ -n "$XDG_RUNTIME_DIR" ] && export PULSE_RUNTIME_PATH="$XDG_RUNTIME_DIR/pulse"
fi

/usr/bin/su "$user" -c "/usr/local/bin/uictl $1"

